import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@livekit/components-styles";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import {ClerkProvider} from "@clerk/nextjs";
import { shadcn } from '@clerk/ui/themes'
import Header from "@/components/Header";
import AxiosProvider from "@/components/AxiosProvider";
import {Toaster} from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

          <html lang="en" suppressHydrationWarning>
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <ClerkProvider
              appearance={{
                  theme: shadcn,
              }}
          >
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
                <AxiosProvider>
                    <Toaster />
                    <Header/>
                    {children}
                </AxiosProvider>


          </ThemeProvider>
          </ClerkProvider>

          </body>
          </html>


  );
}
