import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import {ClerkProvider, Show,SignInButton,SignUpButton,UserButton} from "@clerk/nextjs";
import {ModeToggle} from "@/components/ModeToggle";
import { shadcn } from '@clerk/ui/themes'
import Header from "@/components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

          <html lang="en" suppressHydrationWarning>
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange

          >
              <ClerkProvider
                  appearance={{
                      theme: shadcn,
                  }}
              >
                  <Header/>
                  {children}
              </ClerkProvider>
          </ThemeProvider>

          </body>
          </html>


  );
}
